# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2025 Alyssa Ross <hi@alyssa.is>

[package]
name = "mount-flatpak"
edition = "2024"

[dependencies]
libc = "0.2.177"
pathrs = "0.2.1"
rustix = "1.1.2"
